FROM php:8.0-fpm

ARG user=www-data
ARG uid=33
ARG gid=33

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

USER $user
RUN composer global require laravel/installer

WORKDIR /var/www/html

RUN mkdir storage && chown -R $user:$user storage bootstrap/cache
