services:
  nginx:
    image: nginx:1.27.00
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./Docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: L1sport
      volumes:
        - ./Data/mysql_db:/var/lib/mysql 
    ports:
      - "3308:3306"
